name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and test go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download dependencies
      run: go get -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
